#!/bin/bash

# Atlas Node - One-command setup

set -e

echo "🚀 Setting up Atlas Node..."

# Install Docker if needed
if ! command -v docker &> /dev/null; then
    echo "📦 Installing Docker..."
    curl -fsSL https://get.docker.com | sh
fi

# Install ufw if needed
if ! command -v ufw &> /dev/null; then
    echo "🔥 Installing ufw firewall..."
    apt update -qq && apt install -y ufw
fi

# Load .env if exists, otherwise generate
if [ -f .env ]; then
    echo "📝 Using existing .env..."
    source .env

    # Validate required vars
    if [ -z "$REALITY_PRIVATE_KEY" ] || [ -z "$REALITY_PUBLIC_KEY" ] || [ -z "$SHORT_ID" ]; then
        echo "❌ .env is missing required fields!"
        exit 1
    fi

    REALITY_DEST=${REALITY_DEST:-www.github.com:443}
    REALITY_SERVER_NAMES=${REALITY_SERVER_NAMES:-www.github.com}
else
    echo "🔑 Generating Reality keys..."
    KEYS=$(docker run --rm ghcr.io/xtls/xray-core:latest x25519)
    REALITY_PRIVATE_KEY=$(echo "$KEYS" | grep "PrivateKey" | awk '{print $2}')
    REALITY_PUBLIC_KEY=$(echo "$KEYS" | grep "Password" | awk '{print $2}')
    SHORT_ID=$(openssl rand -hex 8)
    REALITY_DEST=${REALITY_DEST:-www.github.com:443}
    REALITY_SERVER_NAMES=${REALITY_SERVER_NAMES:-www.github.com}
    
    # Save to .env for future reference
    cat > .env << ENVEOF
# Generated by setup.sh on $(date)
REALITY_PRIVATE_KEY=$REALITY_PRIVATE_KEY
REALITY_PUBLIC_KEY=$REALITY_PUBLIC_KEY
SHORT_ID=$SHORT_ID
REALITY_DEST=$REALITY_DEST
REALITY_SERVER_NAMES=$REALITY_SERVER_NAMES

# Add API_SECRET manually (generate with: openssl rand -hex 32)
API_SECRET=
ENVEOF
    echo "✅ Keys saved to .env"
fi

# Write config.json
echo "📝 Writing config.json..."
cat > xray/config.json << EOF
{
  "log": {"loglevel": "warning"},
  "inbounds": [{
    "port": 443,
    "protocol": "vless",
    "settings": {
      "clients": [],
      "decryption": "none"
    },
    "streamSettings": {
      "network": "tcp",
      "security": "reality",
      "realitySettings": {
        "show": false,
        "dest": "$REALITY_DEST",
        "xver": 0,
        "serverNames": ["$REALITY_SERVER_NAMES"],
        "privateKey": "$REALITY_PRIVATE_KEY",
        "shortIds": ["$SHORT_ID"]
      }
    }
  }],
  "outbounds": [{"protocol": "freedom"}]
}
EOF

echo "✅ Config created!"

# Configure firewall
echo "🔥 Configuring firewall..."
if command -v ufw &> /dev/null; then
    ufw allow 22/tcp     # SSH (don't lock yourself out!)
    ufw allow 443/tcp    # Xray
    yes | ufw enable
    echo "✅ Firewall enabled (ports 22, 443)"
else
    echo "⚠️  ufw not found - install with: apt install -y ufw"
fi

# Start container
echo "🚀 Starting Xray..."
docker compose up -d

# Show setup info
SERVER_IP=$(curl -4 -s ifconfig.me 2>/dev/null || echo "YOUR_SERVER_IP")

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║              ✅ Atlas Node Setup Complete!               ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Node Registration Details:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Server IP:    $SERVER_IP"
echo "Public Key:   $REALITY_PUBLIC_KEY"
echo "Short ID:     $SHORT_ID"
echo "Server Names: $REALITY_SERVER_NAMES"
echo "Destination:  $REALITY_DEST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  IMPORTANT: Complete these steps:"
echo ""
echo "1. Add API_SECRET to .env file:"
echo "   nano .env"
echo "   API_SECRET=\$(openssl rand -hex 32)"
echo ""
echo "2. Start the containers:"
echo "   docker compose up -d"
echo ""
echo "3. Verify agent is running:"
echo "   curl http://localhost:3000/health"
echo ""
echo "4. Register this node in Atlas Control using /admin_add_node"
echo "   Use the details above when prompted"
echo ""
echo "🚀 After registration, users can create VPNs via Telegram!"
echo ""
